

== Interoperability


This EHF guide is based on {EIF}[European Interoperability Framework 2.0].

It applies the Framework as follows:

. *Legal Interoperability*
  * Legal:
    **   {EU_Dir_24}[Directive 2014/24/EU]
    **  {EU_Dir_25}[Directive 2014/25/EU]
    **   {Reg_910}[Regulation 910/2014]

. *Organizational interoperability*

*   Organization (Organization/Business):
    **   This EHF guide supports only B2G
    **   This EHF guide supports cross border, regional and domestic tendering procedures in EU and EEA
    **   This EHF guide can function as a standardized EDI agreement within a trading community
    **   This EHF guide supports linking of business processes within the sending and receiving organization.
*   Organization (Process):
    **   This EHF guide supports a set of _“common business processes”_ that are assumed to be supported by most enterprises whether public or private. These are processes that are used widely or understood as being relevant for most companies.

. *Semantic interoperability*

*   Semantic:

** A minimum set of information elements required to conduct a procurement procedure. The set of information elements is assumed to be sufficient to support organizational business and processing requirements stated above.

***   A CORE:
        **** _Data model_, a set of elements that the receiver MUST be able to process.
        **** _Business rules_, a set of business rules that ensure a common way of processing the information elements. The rules are stated in a way that allows for automated validation of document instances.

. *Technical interoperability*


*   Technical Interaction (Process and semantic implementation):
    **   Binding to {SBDH}[SBDH] v1.3
    **   {ASIC}[ASIC-E] container with {CAdES}[CAdES] signature.
    **   Binding to {UBL}[UBL 2.1]:
    *** CWA 17027-212 UBL binding - Trdm083 Call for Tenders.docx
    ** {ESPD_github}
    **   Validation:
        *** BIIRULES-UBL-T83.sch
        *** NOGOV-UBL-T83.sch
        *** {CfT_xsd}[UBL-Tender-2.1.xsd]
        *** {ESPD_github}
