
= European Single Procurement Document (ESPD)

Article 59 of the new Public Procurement Directive 2014/24/EC introduced a new concept, the European Single Procurement Document ({ESPD}) which is a self-declaration document intended for preliminary evidence in a public procurement procedure. The main objective of the {ESPD} is to reduce the administrative burden and lead to considerable simplification of participation in public procurement procedures for buyers and suppliers. {ESPD} will reduce the burden by removing the need to produce a substantial number of certificates and documentation related to exclusion and selection criteria.

Documentation and services related to {ESPD} are provided by the European Commission. This is an overview of the currently available resources:

* {ESPD_Service} ({ESPD_doc})
* {ESPD_model}
* {ESPD_github}

Implementers of this profile attach ESPD Request/Response by adding a DocumentReference. Values to be used:

`cac:DocumentReference/cbc:DocumentTypeCode`:: 916 (Related document)
`cbc:DocumentDescription`:: ESPD Request/Response

Please also see <<espd_descr, chapter for description>> for further details.
