

== Interoperability


This EHF guide is based on {EIF}[European Interoperability Framework 2.0].

It applies the Framework as follows:

. *Legal Interoperability*
  * Legal:
    **   {EU_Dir_24}[Directive 2014/24/EU]
    **  {EU_Dir_25}[Directive 2014/25/EU]
    **   {Reg_910}[Regulation 910/2014]

. *Organizational interoperability*

*   Organization (Organization/Business):
    **   This EHF guide supports only B2G
    **   This EHF guide supports cross border, regional and domestic tendering procedures in EU and EEA
    **   This EHF guide can function as a standardized EDI agreement within a trading community
    **   This EHF guide supports linking of business processes within the sending and receiving organization.
*   Organization (Process):
    **   This EHF guide supports a set of _“common business processes”_ that are assumed to be supported by most enterprises whether public or private. These are processes that are used widely or understood as being relevant for most companies.

. *Semantic interoperability*

*   Semantic:

** A minimum set of information elements required to conduct a procurement procedure. The set of information elements is assumed to be sufficient to support organizational business and processing requirements stated above.

***   A CORE:
        **** _Data model_, a set of elements that the receiver MUST be able to process.
        **** _Business rules_, a set of business rules that ensure a common way of processing the information elements. The rules are stated in a way that allows for automated validation of document instances.


. *Technical interoperability*

*   Technical Interaction (Process and semantic implementation):
    **   Binding to {SBDH}[SBDH] v1.3
    **   {ASIC}[ASIC-E] container with {CAdES}[CAdES] signature.
    **   Binding to {UBL}[UBL 2.1]:
    *** CWA 17027-218 UBL binding - Trdm090 Tender
    *** CWA 17027-205 UBL binding - Trdm045 Tender Reception Notification
    *** CWA 17028-213 UBL binding - Trdm068 Pre-award catalogue
    ** {ESPD_github}
    **   Validation:
        *** BIIRULES-UBL-T90.sch
        *** BIIRULES-UBL-T45.sch
        *** BIIRULES-UBL-T68.sch
        *** NOGOV-UBL-T90.sch
        *** NOGOV-UBL-T45.sch
        *** NOGOV-UBL-T68.sch
        *** {Tender_xsd}[UBL-Tender-2.1.xsd]
        *** {Tender_Rec_xsd}[UBL-TenderReceipt-2.1.xsd]
      *** {Catalogue_xsd}[UBL-Catalogue-2.1.xsd]
      *** {ESPD_github}
