
= Introduction to eSENS eTendering and BIS


This document provides a set of specifications for implementing a business process. The document is concerned with clarifying requirements for ensuring interoperability in eProcurement and provides guidelines for supporting these requirements and how to implement. The following are the basis for this work:

****
[IMPORTANT]
====
These CEN WS/BII3 <<profiles, profiles>>, and the corresponding UBL binding documents, as well as the ESPD Documentation are the basis for this work:

* CWA 17027-112 Profile 47 - Call for Tenders
* CWA 17027-212 UBL binding document, Trdm083 Call for tenders
* European commission documentation for ESPD

*And it is important that implementers are well known with the content of these documents to ensure implementations that are valid and of high quality.*
====
****


*The purpose* of this document is to describe a common format for exchanging messages in a procurement procedure, to facilitate an efficient implementation and increased use of electronic tendering based on this format.
